### PR TITLE
This will allow generic smtp servers through configuration

### PR DESCRIPTION
**Pull request by jovandeginste**
Take care to update your `.ini` file after this upgrade,
some changes are 'breaking'...

### CODE REVIEW

**Comment by jovandeginste** [comment]
I couldn't get the gmail authentication to work, but I have a perfectly fine SMTP server inside my network to use, so I did some work to get this plugin more generic. Now my wife can finally get her weight by mail :-)

**Comment by keptenkurk** [comment]
Will give the gmail a go

**Comment by keptenkurk** [comment]
Gmail works fine as it was with the proposed settings in example.ini. Thanks again for this add-on!

**Comment by jovandeginste** [comment]
Maybe the issue is my 2fa. I can try again later...

**Pull request merged**
