### PR TITLE
More sensors! Domoticz!

### PR DESCRIPTION
**Pull request by Tristan79**
More sensors for Domoticz, fat %, muscle %, tbw %, bone kg, BMI, and BMR :-)

### CODE REVIEW

**Comment by Tristan79** [comment]
Uhm,

I accidently deleted from the config:

```
#Uncomment [Google] to enable Google FIT updating		
 -#[Google]
```

And in line 86 of BS440domoticz.py there is a print statement (print i) which should not have been there...

**Comment by keptenkurk** [comment]
To be honoust: I'm not a Github guru but this pull request looks to contain all kinds of debugging steps. I can figure out you would like to store more of the scale values into Domoticz virtual sensors. 
I'm willing to merge this but would like to see a pull request which builds on the master branch. Would that be possible?

**Comment by keptenkurk** [comment]
BTW: have been standing on the scale for over half a year now. The additional values like fat etc. are mostly calculated directly from age, height and weight. Don't expect too much from it  ;-)

**Comment by Tristan79** [comment]
No problem :-) You get a proper request. I forgot to edit some stuff, and I
will the change the weight_id back to scale_id to make it more backwards
compatible ;-) But not tonight.
Fixing [iBrew](https://github.com/Tristan79/iBrew)... :-)

**Pull request closed without merging**
