### PR TITLE
Fix BS440csv for plugin structure

### PR DESCRIPTION
**Pull request by DjZU**
@keptenkurk BS440test.py has been very useful for this, thanks!

### CODE REVIEW

**Comment by DjZU** [comment]
@keptenkurk I just found out that you already fixed that 2 days ago. Still in this version the empty BS440csv directory is not needed anymore.

**Comment by keptenkurk** [comment]
Pulled it manually because of conflicts i don't know how to resolve...

**Comment by DjZU** [comment]
I guess conflicted because I made changes from an older version that the one that was in the directory when the request has been pulled. Hope you don't have the issue with CRLF thing this time.

**Comment by keptenkurk** [comment]
All fine. The CRLF thing only bothers when the OS needs to determine the interpreter to be used through the #! directive...

**Pull request closed without merging**
